---
<<<<<<< HEAD
- hosts: all
=======
- hosts: web
>>>>>>> 272ae1813a02c268b97aaa7fd407ac3819ce10c3
  become: true
  gather_facts: true
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"

  roles:
    # - geerlingguy.repo-epel
    - geerlingguy.firewall
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql

  tasks:
    - name: Ensure php-cli is installed for ubuntu
      apt:
        name: libapache2-mod-php 
        state: present

    - name: Delete existing index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy html file to web server
      template:
        src: index.php
        dest: /var/www/html/index.php
        owner: root
        group: root
        mode: 0644
<<<<<<< HEAD
=======

    - debug: var=hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']


  
    
>>>>>>> 272ae1813a02c268b97aaa7fd407ac3819ce10c3
