---
- hosts: all
  become: true

  vars:
    haproxy_frontend_bind_address: '*'
    haproxy_backend_mode: 'http'
    haproxy_backend_balance_method: 'roundrobin'
    haproxy_backend_servers:
      - name: app1
        address: 192.168.3.11:80
      - name: app2
        address: 192.168.3.13:80

  pre_tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

  roles:
    - role: geerlingguy.haproxy

  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']
