---
firewall_allowed_tcp_ports:
  - "22"
  - "3306"

mysql_root_password: "password"

mysql_databases:
  - name: example_db
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: example_user
    password: "secret"
    host: "%"
    priv: "example_db.*:ALL"